services:
  - type: web
    name: webscraper-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "python -m pip install --upgrade pip && python -m pip install --no-cache-dir -r backend/requirements-deployment-fix.txt && python -m playwright install chromium"
    startCommand: "cd /opt/render/project/src && python backend/main-deployment-fix.py"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PIP_NO_CACHE_DIR
        value: 1
    healthCheckPath: /api/health