services:
  # Backend API Service
  - type: web
    name: webscraper-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt && python -m playwright install chromium"
    startCommand: "python backend/main.py"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: webscraper-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 10000
      - key: VITE_RENDER_BACKEND_URL
        value: https://webscraper-backend.onrender.com
    staticPublishPath: ./dist